// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateTeams() {
  return window['go']['main']['App']['GenerateTeams']();
}

export function GetMatchState() {
  return window['go']['main']['App']['GetMatchState']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ReceiverStatus() {
  return window['go']['main']['App']['ReceiverStatus']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartReceiver() {
  return window['go']['main']['App']['StartReceiver']();
}

export function StopReceiver() {
  return window['go']['main']['App']['StopReceiver']();
}
