// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GenerateTeams():Promise<Array<domain.Team>>;

export function GetMatchState():Promise<domain.MatchState>;

export function GetSettings():Promise<domain.PublicSettings>;

export function ReceiverStatus():Promise<domain.ReceiverStatus>;

export function SaveSettings(arg1:domain.PublicSettings):Promise<void>;

export function StartReceiver():Promise<void>;

export function StopReceiver():Promise<void>;
